### ISSUE TITLE
🎨 Mock User Account Main Page UI

### ISSUE THREAD

**Issue by andrewjumanca** [GitRepsCommunity/platform#69]
## Summary
- Identifying data needs.
- Visualizing user flow.
- Gathering early feedback.
- Supporting iterative design.
- Ensuring clear communication.
- Saving time and resources.

## Tasks

- [ ] Ideate on what important data are necessary
- [ ] Create a general flow of the basic data positions (e.g Name, Profile Pic, Default Description)
- [ ] add user flow to understand the data connections necessary for the application
