### ISSUE TITLE
Fix GitHub Icon

### ISSUE THREAD

**Issue by GitRepsOfficial** [GitRepsCommunity/platform#83]
## Summary
Fix the broken GitHub icon on the sign up button.
![Platform](https://github.com/GitRepsCommunity/platform/assets/137091252/1c92d2f8-176a-457c-8f1e-f5d055310d4d)

## Tasks
- [x] Install the [inline_svg](https://github.com/jamesmartin/inline_svg) gem.
- [x] Add the svg file to assets directory: `app/assets/images/github-mark-white.svg`
- [x] Update view to reference the svg file using `inline_svg_tag`

```ruby
<%= inline_svg_tag "github-mark-white.svg", class: 'h-18 w-18 bg-black' %>
```
