### ISSUE TITLE
Add job title to profile

### ISSUE THREAD

**Issue by GitRepsOfficial** [GitRepsCommunity/platform#84]
## Summary
Allow users to edit their profile and update the job title so that it displays on the profile page.
 
![Platform](https://github.com/GitRepsCommunity/platform/assets/137091252/17393ec3-3cb1-4948-9f15-2ade6f81ba74)

## Definition of Done
> How do we know when this feature is complete?

* The `job_title` field exists in the database on the `profiles` table
* Submitting the edit profile form with a value in the `job_title` field will save to the database
* The `job_title` for a given profile in the database will be rendered on the profile view

## Tasks
- [ ] Add `job_title` field to `Profile` model
- [ ] Add `:job_title` to permitted params in `profiles_controller`
- [ ] Replace the hard-coded text "Job title goes here" with `@profile.job_title`
